repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
    -   id: check-yaml
        always_run: true
    -   id: end-of-file-fixer
        always_run: true
    -   id: trailing-whitespace
        always_run: true

-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.8.4
    hooks:
        - id: ruff
          always_run: true
          types_or: [ python, pyi ]
          args: [ --fix, --exclude=__init__.py]
        - id: ruff-format
          always_run: true
          types_or: [ python, pyi]
          args: [--line-length=85]

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.13.0
    hooks:
    -   id: mypy
        args: [--ignore-missing-imports,
               --allow-redefinition,
               --follow-imports=silent,
               --disallow-untyped-defs,
               --warn-unreachable,
               --show-error-context,
               --exclude=__init__.py]
